# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class AlertCreateRequest(BaseModel):
    """
    Body for POST /v1/alerts (usage-billed per active alert per month).
    """

    division: str = Field(
        ...,
        description="Comma-separated sport-valid division scope, e.g. 'D1,NAIA,NJCAA-D1'.",
        title="Division",
    )
    enabled: bool | None = Field(
        True, description="Create the alert paused by setting false.", title="Enabled"
    )
    filters: dict[str, Any] = Field(
        ...,
        description="Filter DSL; see /v1/filters/catalog and the docs.",
        title="Filters",
    )
    gender: str | None = Field(
        None,
        description="'men' or 'women'; ignored for single-gender sports.",
        title="Gender",
    )
    name: constr(min_length=1, max_length=255) = Field(
        ..., description="Human label for the alert.", title="Name"
    )
    sport: str = Field(
        ..., description="e.g. 'soccer', 'basketball', 'baseball'.", title="Sport"
    )
    webhook_url: str | None = Field(
        None,
        description="HTTPS endpoint for match notifications (delivery coming soon; stored now).",
        title="Webhook Url",
    )


class AlertDeleteResponse(BaseModel):
    """
    Acknowledgement for DELETE /v1/alerts/{alert_id}.
    """

    deleted: bool | None = Field(True, title="Deleted")


class AlertMatchEntry(BaseModel):
    """
    A portal entry that matched an alert.
    """

    id: int = Field(..., title="Id")
    matched_at: AwareDatetime | None = Field(None, title="Matched At")
    player: dict[str, Any] | None = Field(
        None,
        description="Matched portal player: name, team, division, sport_path, status, is_grad_transfer.",
        title="Player",
    )


class AlertMatchListResponse(BaseModel):
    """
    Envelope for GET /v1/alerts/{alert_id}/matches.
    """

    data: list[AlertMatchEntry] = Field(..., title="Data")


class AlertSummary(BaseModel):
    """
    A portal watch alert created via the API.
    """

    created_at: AwareDatetime | None = Field(None, title="Created At")
    division: str | None = Field(None, title="Division")
    enabled: bool | None = Field(True, title="Enabled")
    filters: dict[str, Any] | None = Field(
        None, description="Filter DSL; see GET /v1/filters/catalog.", title="Filters"
    )
    id: str = Field(..., title="Id")
    last_evaluated_at: AwareDatetime | None = Field(
        None,
        description="When the alert was last evaluated against the live portal feed.",
        title="Last Evaluated At",
    )
    last_match_count: int | None = Field(
        0,
        description="Match count from the most recent evaluation.",
        title="Last Match Count",
    )
    name: str = Field(..., title="Name")
    sport_path: str | None = Field(None, title="Sport Path")
    webhook_delivery: str | None = Field(
        "no_endpoint_registered",
        description="'enabled' when at least one enabled webhook endpoint in the console is subscribed to alert.triggered (and matches webhook_url, if set); otherwise 'no_endpoint_registered'. Register endpoints in the console; polling GET /v1/alerts/{id}/matches always works.",
        title="Webhook Delivery",
    )
    webhook_url: str | None = Field(None, title="Webhook Url")


class ApiErrorDetail(BaseModel):
    """
    The error object inside the `{ "error": {...} }` envelope. May carry
    additional context keys beyond the three fixed ones.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    code: str = Field(
        ...,
        description="Stable machine-readable code for this specific error.",
        examples=["invalid_scope"],
        title="Code",
    )
    message: str = Field(
        ...,
        description="Human-readable explanation.",
        examples=["Unknown sport 'curling'."],
        title="Message",
    )
    type: str = Field(
        ...,
        description="Error category, e.g. 'invalid_request', 'not_found', 'rate_limited'.",
        examples=["invalid_request"],
        title="Type",
    )


class ApiErrorResponse(BaseModel):
    """
    Envelope returned for every 4xx/5xx from /v1, except 422 request
    validation errors which use FastAPI's standard `{"detail": [...]}` shape.
    """

    error: ApiErrorDetail


class ExportCreateRequest(BaseModel):
    """
    Body for POST /v1/exports (usage-billed by result size).

    One export = one dataset in one sport/division scope, written as a single
    gzipped flat file. Use the optional filters to keep large datasets under
    the row cap.
    """

    conference: str | None = Field(
        None,
        description="Conference filter (players/teams/coaches).",
        title="Conference",
    )
    dataset: str = Field(
        ..., description="'players' | 'teams' | 'games' | 'coaches'.", title="Dataset"
    )
    division: str = Field(
        ...,
        description="Comma-separated sport-valid division scope, e.g. 'D1,NAIA,NJCAA-D1'.",
        title="Division",
    )
    format: str | None = Field(
        "csv",
        description="'csv' or 'jsonl'; the file is always gzipped.",
        title="Format",
    )
    gender: str | None = Field(
        None,
        description="'men' or 'women'; ignored for single-gender sports.",
        title="Gender",
    )
    season: str | None = Field(
        None,
        description="Season filter (championship year, e.g. '2025').",
        title="Season",
    )
    sport: str = Field(
        ..., description="e.g. 'soccer', 'basketball', 'baseball'.", title="Sport"
    )


class ExportCreateResponse(BaseModel):
    """
    Acknowledgement for POST /v1/exports; poll GET /v1/exports/{export_id}.
    """

    export_id: str = Field(
        ..., examples=["b3f9c1d2-4a5e-4f6b-8c7d-9e0f1a2b3c4d"], title="Export Id"
    )
    status: str = Field(..., examples=["queued"], title="Status")


class ExportJobStatus(BaseModel):
    """
    Status of an export job. `download_url` appears once the job succeeds and
    is minted fresh (short-lived) on every status read; re-poll for a new one.
    The stored file itself expires at `expires_at`.
    """

    billed_usd: float | None = Field(
        None,
        description="Amount billed for this export; present once billing lands.",
        title="Billed Usd",
    )
    bytes: int | None = Field(None, description="Compressed file size.", title="Bytes")
    created_at: AwareDatetime | None = Field(None, title="Created At")
    dataset: str = Field(..., title="Dataset")
    download_expires_at: AwareDatetime | None = Field(
        None,
        description="When `download_url` stops working; poll again for a fresh one.",
        title="Download Expires At",
    )
    download_url: str | None = Field(
        None,
        description="Short-lived signed download URL; present while status is 'succeeded'.",
        title="Download Url",
    )
    error: str | None = Field(
        None, description="Failure detail when status is 'failed'.", title="Error"
    )
    expires_at: AwareDatetime | None = Field(
        None,
        description="When the stored file is deleted (status becomes 'expired').",
        title="Expires At",
    )
    export_id: str = Field(..., title="Export Id")
    finished_at: AwareDatetime | None = Field(None, title="Finished At")
    format: str = Field(..., title="Format")
    params: dict[str, Any] | None = Field(
        None, description="Echo of the requested scope and filters.", title="Params"
    )
    row_count: int | None = Field(None, title="Row Count")
    started_at: AwareDatetime | None = Field(None, title="Started At")
    status: str = Field(
        ...,
        description="queued | running | succeeded | failed | expired",
        title="Status",
    )


class ExportListPage(BaseModel):
    """
    One page of export jobs (newest first).
    """

    data: list[ExportJobStatus] = Field(..., title="Data")
    has_more: bool | None = Field(
        False, description="True when another page is available.", title="Has More"
    )
    next_cursor: str | None = Field(
        None,
        description="Opaque cursor for the next page; null when there are no more results.",
        examples=["eyJvZmZzZXQiOiAyNX0="],
        title="Next Cursor",
    )


class FreshnessInfo(BaseModel):
    """
    When the source page behind a record was last read. `observed_at` is
    the last fetch that was ingested; `changed_at` the last time the page's
    content actually changed; `next_check_at` when the next fetch is due
    under the seasonal cadence policy (see the Data sources and freshness
    section). Null when the program has never been read through the target
    registry.
    """

    cadence_hours: int | None = Field(
        None,
        description="Current refresh interval for this record, in hours.",
        title="Cadence Hours",
    )
    changed_at: AwareDatetime | None = Field(None, title="Changed At")
    checked_at: AwareDatetime | None = Field(None, title="Checked At")
    next_check_at: AwareDatetime | None = Field(None, title="Next Check At")
    observed_at: AwareDatetime | None = Field(None, title="Observed At")


class GameFixture(BaseModel):
    """
    One game as listed by GET /v1/games — a side-anchored fixture (home/away,
    never perspective-relative). A game between teams in different divisions is
    visible in either division's scope.
    """

    attendance: int | None = Field(None, title="Attendance")
    away_conference_record: str | None = Field(None, title="Away Conference Record")
    away_period_scores: Any = Field(None, title="Away Period Scores")
    away_score: int | None = Field(None, title="Away Score")
    away_team_id: int | None = Field(None, title="Away Team Id")
    away_team_name: str | None = Field(None, title="Away Team Name")
    away_team_record: str | None = Field(None, title="Away Team Record")
    boxscore_url: str | None = Field(None, title="Boxscore Url")
    game_date: str | None = Field(
        None, description="ISO date, e.g. '2025-10-18'.", title="Game Date"
    )
    game_time: str | None = Field(None, title="Game Time")
    home_conference_record: str | None = Field(None, title="Home Conference Record")
    home_period_scores: Any = Field(
        None, description="Line score by period/segment.", title="Home Period Scores"
    )
    home_score: int | None = Field(None, title="Home Score")
    home_team_id: int | None = Field(
        None,
        description="Team id; use with GET /v1/teams/{team_id}.",
        title="Home Team Id",
    )
    home_team_name: str | None = Field(None, title="Home Team Name")
    home_team_record: str | None = Field(
        None, description="Record at time of game.", title="Home Team Record"
    )
    id: int | None = Field(
        None, description="Game id; use with GET /v1/games/{game_id}.", title="Id"
    )
    location: str | None = Field(None, title="Location")
    neutral_site: bool | None = Field(None, title="Neutral Site")
    season: str | None = Field(
        None, description="Championship year, e.g. '2025'.", title="Season"
    )
    sport_path: str | None = Field(
        None, description="Gendered sport key, e.g. 'mens-soccer'.", title="Sport Path"
    )
    status: str | None = Field(
        None,
        description="scheduled | final | postponed | cancelled | forfeit",
        title="Status",
    )
    venue: str | None = Field(None, title="Venue")
    winner_team_id: int | None = Field(
        None,
        description="Null for ties (or an untracked winner).",
        title="Winner Team Id",
    )


class GamePage(BaseModel):
    """
    One page of games.
    """

    data: list[GameFixture] = Field(..., title="Data")
    has_more: bool | None = Field(
        False, description="True when another page is available.", title="Has More"
    )
    next_cursor: str | None = Field(
        None,
        description="Opaque cursor for the next page; null when there are no more results.",
        examples=["eyJvZmZzZXQiOiAyNX0="],
        title="Next Cursor",
    )


class GameSummary(BaseModel):
    """
    A game with everything held for it, passed through under `detail`:
    the fixture (`detail.game`), team/player box scores, play-by-play, and
    (where covered) drives and recaps. Per-sport shapes vary.
    """

    detail: dict[str, Any] | None = Field(
        None,
        description="Complete game payload: `game` (the fixture), `team_stats`, `player_stats`, `play_by_play`, and per-sport extras (drives, recaps). Shape varies by sport.",
        title="Detail",
    )
    id: Any = Field(None, description="Game id as requested.", title="Id")


class ManagedAthleteAccessEntry(BaseModel):
    """
    One delegated read that returned contact fields.
    """

    api_key_id: str | None = Field(None, title="Api Key Id")
    capability: str = Field(..., title="Capability")
    division: str | None = Field(None, title="Division")
    grant_id: str = Field(..., title="Grant Id")
    id: int = Field(..., title="Id")
    occurred_at: AwareDatetime | None = Field(None, title="Occurred At")
    player_id: int | None = Field(None, title="Player Id")
    row_count: int | None = Field(0, title="Row Count")
    sport_path: str | None = Field(None, title="Sport Path")
    team_id: int | None = Field(None, title="Team Id")


class ManagedAthleteAccessPage(BaseModel):
    """
    A page of delegated-access audit events.
    """

    data: list[ManagedAthleteAccessEntry] = Field(..., title="Data")
    has_more: bool | None = Field(
        False, description="True when another page is available.", title="Has More"
    )
    next_cursor: str | None = Field(
        None,
        description="Opaque cursor for the next page; null when there are no more results.",
        examples=["eyJvZmZzZXQiOiAyNX0="],
        title="Next Cursor",
    )


class ManagedAthleteCreateRequest(BaseModel):
    """
    Invite one athlete to authorize your account.
    """

    email: constr(max_length=255) | None = Field(
        None,
        description="Where to send the invitation. Optional: we default to the athlete's on-file contact. A supplied address is accepted only when it matches that contact or the athlete's school .edu domain.",
        title="Email",
    )
    organization_name: constr(max_length=160) | None = Field(
        None,
        description="How your platform is named in the invitation email.",
        title="Organization Name",
    )
    player_id: int = Field(
        ...,
        description="The athlete's player id (GET /v1/players/search).",
        title="Player Id",
    )
    sport_path: str | None = Field(
        None,
        description="The athlete's sport path, e.g. 'womens-soccer'. Speeds up the lookup.",
        title="Sport Path",
    )


class ManagedAthleteEntry(BaseModel):
    """
    One athlete's authorization for your account.
    """

    athlete_email: str | None = Field(
        None,
        description="Masked address the invitation went to.",
        title="Athlete Email",
    )
    athlete_name: str | None = Field(None, title="Athlete Name")
    consented_at: AwareDatetime | None = Field(None, title="Consented At")
    created_at: AwareDatetime | None = Field(None, title="Created At")
    id: str = Field(
        ...,
        description="Grant id; use with the other /v1/athletes endpoints.",
        title="Id",
    )
    invite_expires_at: AwareDatetime | None = Field(None, title="Invite Expires At")
    invited_at: AwareDatetime | None = Field(None, title="Invited At")
    organization_name: str | None = Field(None, title="Organization Name")
    person_id: int | None = Field(None, title="Person Id")
    player_id: int | None = Field(None, title="Player Id")
    revoked_at: AwareDatetime | None = Field(None, title="Revoked At")
    revoked_by: str | None = Field(
        None, description="org | athlete | admin, when revoked.", title="Revoked By"
    )
    sport_path: str | None = Field(None, title="Sport Path")
    status: str = Field(
        ...,
        description="invited | active | declined | revoked | expired.",
        title="Status",
    )


class ManagedAthletePage(BaseModel):
    """
    A page of managed athletes.
    """

    data: list[ManagedAthleteEntry] = Field(..., title="Data")
    has_more: bool | None = Field(
        False, description="True when another page is available.", title="Has More"
    )
    next_cursor: str | None = Field(
        None,
        description="Opaque cursor for the next page; null when there are no more results.",
        examples=["eyJvZmZzZXQiOiAyNX0="],
        title="Next Cursor",
    )


class ManagedAthleteRevokeResponse(BaseModel):
    id: str = Field(..., title="Id")
    status: str = Field(..., title="Status")


class MovementSubject(BaseModel):
    """
    Display snapshot of the person a movement is about, taken from the
    event payload at observation time. Contact fields are never included.
    """

    class_year: str | None = Field(
        None, description="Players only.", title="Class Year"
    )
    from_title: str | None = Field(
        None, description="Coaches, title changes only.", title="From Title"
    )
    is_head: bool | None = Field(
        None, description="Coaches only — head-coach role.", title="Is Head"
    )
    name: str | None = Field(None, title="Name")
    position: str | None = Field(None, description="Players only.", title="Position")
    title: str | None = Field(
        None, description="Coaches only — current title.", title="Title"
    )
    to_title: str | None = Field(
        None, description="Coaches, title changes only.", title="To Title"
    )


class PlayerDetail(BaseModel):
    """
    A single player's profile with season stats, accolades, and (when the
    player is linked to a person) their cross-program career.
    """

    accolades: Any | None = Field(
        None, description="Awards and honors, when held.", title="Accolades"
    )
    career: Any | None = Field(
        None,
        description="Cross-program career topology (stints across schools), when linked.",
        title="Career",
    )
    class_year: str | None = Field(None, title="Class Year")
    conference: str | None = Field(None, title="Conference")
    division: str | None = Field(None, title="Division")
    headshot_url: str | None = Field(None, title="Headshot Url")
    height: str | None = Field(None, title="Height")
    hometown: str | None = Field(None, title="Hometown")
    id: int | None = Field(None, title="Id")
    is_verified: bool | None = Field(None, title="Is Verified")
    name: str | None = Field(None, title="Name")
    person_id: Any = Field(
        None,
        description="Cross-program person id; use with GET /v1/persons/{person_id}.",
        title="Person Id",
    )
    position: str | None = Field(None, title="Position")
    season_stats: Any | None = Field(
        None,
        description="Per-season stat rows; shape varies by sport.",
        title="Season Stats",
    )
    team: str | None = Field(None, description="Team/school name.", title="Team")


class PlayerSearchRequest(BaseModel):
    """
    Public body for POST /v1/players/search.

    Scope (`sport`/`gender`/`division`) is required and bounds every result.
    The remaining fields are a curated, sport-agnostic subset of the app's
    manual-search filters; richer catalog-driven filters come in a later rev.
    """

    class_year: str | None = Field(None, title="Class Year")
    conference: str | None = Field(None, title="Conference")
    cursor: str | None = Field(
        None,
        description="Opaque pagination cursor from a prior response.",
        title="Cursor",
    )
    division: str = Field(
        ...,
        description="Comma-separated sport-valid division scope, e.g. 'D1,NAIA,NJCAA-D1'.",
        title="Division",
    )
    gender: str | None = Field(
        None,
        description="'men' or 'women'; ignored for single-gender sports.",
        title="Gender",
    )
    hometown: str | None = Field(None, title="Hometown")
    limit: conint(ge=1, le=100) | None = Field(
        25, description="Page size (max 100).", title="Limit"
    )
    major: str | None = Field(None, title="Major")
    position: str | None = Field(None, title="Position")
    season: str | None = Field(None, title="Season")
    sort_by: str | None = Field(
        None, description="Stat field to sort by.", title="Sort By"
    )
    sort_order: str | None = Field(
        "descending", description="'ascending' or 'descending'.", title="Sort Order"
    )
    sport: str = Field(
        ..., description="e.g. 'soccer', 'basketball', 'baseball'.", title="Sport"
    )
    team_name: str | None = Field(None, title="Team Name")


class PlayerSeasonsResponse(BaseModel):
    """
    Season-history view for one player. All three keys are always present;
    `track_performances` is populated for track & field athletes only.
    """

    accolades: Any | None = Field(
        None, description="Awards and honors, when held.", title="Accolades"
    )
    season_stats: Any | None = Field(
        None,
        description="Per-season stat rows; shape varies by sport.",
        title="Season Stats",
    )
    track_performances: Any | None = Field(
        None,
        description="Track & field performance list; null for other sports.",
        title="Track Performances",
    )


class PlayerSummary(BaseModel):
    """
    A player row as returned by search — identity plus a sport-shaped stat
    bag. Contact fields (email/phone/social) are intentionally omitted.
    """

    class_year: str | None = Field(
        None,
        description="e.g. 'Freshman', 'Sophomore', 'Junior', 'Senior'.",
        title="Class Year",
    )
    conference: str | None = Field(None, title="Conference")
    division: str | None = Field(
        None, description="e.g. 'D1', 'D2', 'D3', 'NAIA', 'NJCAA'.", title="Division"
    )
    headshot_url: str | None = Field(None, title="Headshot Url")
    height: str | None = Field(
        None, description="Formatted height, e.g. '6-2'.", title="Height"
    )
    hometown: str | None = Field(None, title="Hometown")
    id: int | None = Field(
        None, description="Player id; use with GET /v1/players/{player_id}.", title="Id"
    )
    is_verified: bool | None = Field(
        None,
        description="True when the athlete has claimed this profile.",
        title="Is Verified",
    )
    name: str | None = Field(None, title="Name")
    position: str | None = Field(None, title="Position")
    season: str | None = Field(
        None,
        description="Season the stat bag belongs to, e.g. '2025-26'.",
        title="Season",
    )
    stats: dict[str, Any] | None = Field(
        None,
        description="Sport-shaped stat fields; keys vary by sport (see GET /v1/filters/catalog).",
        title="Stats",
    )
    team: str | None = Field(None, description="Team/school name.", title="Team")


class PortalEntry(BaseModel):
    """
    One live transfer-portal entry. `contacts` is present only for callers
    whose key delegates `portal.contact.read` and whose current actor is an
    active verified coach on a Max account for the requested sport.
    """

    conference: str | None = Field(None, title="Conference")
    contacts: dict[str, Any] | None = Field(
        None,
        description="Protected athlete contact info (email/phone/social); requires portal.contact.read plus current active verified coach and Max sport authority.",
        title="Contacts",
    )
    designated_student_athlete: bool | None = Field(
        None, title="Designated Student Athlete"
    )
    division: str | None = Field(None, title="Division")
    first_seen_at: AwareDatetime | None = Field(
        None,
        description="When this entry first appeared in our feed.",
        title="First Seen At",
    )
    id: str | None = Field(None, title="Id")
    initiated_date: str | None = Field(
        None, description="Date the athlete entered the portal.", title="Initiated Date"
    )
    is_grad_transfer: bool | None = Field(None, title="Is Grad Transfer")
    last_seen_at: AwareDatetime | None = Field(
        None,
        description="When this entry was last confirmed present.",
        title="Last Seen At",
    )
    last_updated_date: str | None = Field(
        None,
        description="Date NCAA last updated the record.",
        title="Last Updated Date",
    )
    name: str | None = Field(None, title="Name")
    sport_path: str | None = Field(None, title="Sport Path")
    status: str | None = Field(
        None, description="NCAA record status, e.g. 'INC' (active).", title="Status"
    )
    team: str | None = Field(
        None, description="Current school (matched name when resolved).", title="Team"
    )
    year: str | None = Field(
        None, description="Class year code, e.g. 'FR', 'SO', 'JR', 'SR'.", title="Year"
    )


class PortalPage(BaseModel):
    """
    One page of transfer-portal entries.
    """

    data: list[PortalEntry] = Field(..., title="Data")
    has_more: bool | None = Field(
        False, description="True when another page is available.", title="Has More"
    )
    next_cursor: str | None = Field(
        None,
        description="Opaque cursor for the next page; null when there are no more results.",
        examples=["eyJvZmZzZXQiOiAyNX0="],
        title="Next Cursor",
    )


class PublicQueryRequest(BaseModel):
    """
    Body for POST /v1/query (natural-language query — usage-billed).

    The model is fixed server-side in v1 so billing stays predictable.
    """

    division: str | None = Field(
        "D1",
        description="Comma-separated sport-valid division scope, e.g. 'D1,NAIA,NJCAA-D1'.",
        title="Division",
    )
    gender: str | None = Field(
        None,
        description="'men' or 'women'; ignored for single-gender sports.",
        title="Gender",
    )
    prompt: constr(min_length=1, max_length=4000) = Field(
        ..., description="The question to answer.", title="Prompt"
    )
    sport: str = Field(
        ..., description="e.g. 'soccer', 'basketball', 'baseball'.", title="Sport"
    )


class QueryCreateResponse(BaseModel):
    """
    Acknowledgement for POST /v1/query; poll GET /v1/query/{run_id}.
    """

    run_id: str = Field(
        ..., examples=["9f8a1c2e-6f0b-4f2a-8f0d-3f2b1a9c8e7d"], title="Run Id"
    )
    status: str = Field(..., examples=["queued"], title="Status")


class QueryRunStatus(BaseModel):
    """
    Status of a natural-language query run. `answer` and `usage` appear once
    the run is terminal (usage lands seconds after completion, when billing
    finalizes).
    """

    answer: str | None = Field(
        None,
        description="Final answer text; present once the run is done.",
        title="Answer",
    )
    created_at: AwareDatetime | None = Field(None, title="Created At")
    error: str | None = Field(
        None, description="Failure detail when status is 'error'.", title="Error"
    )
    finished_at: AwareDatetime | None = Field(None, title="Finished At")
    run_id: str = Field(..., title="Run Id")
    started_at: AwareDatetime | None = Field(None, title="Started At")
    status: str = Field(
        ..., description="queued | running | done | error | cancelled", title="Status"
    )
    usage: dict[str, Any] | None = Field(
        None,
        description="Token counts, model, and billed amount; present once billing finalizes.",
        title="Usage",
    )


class RosterEntry(BaseModel):
    """
    A roster member — identity only, no contact fields.
    """

    class_year: str | None = Field(None, title="Class Year")
    headshot_url: str | None = Field(None, title="Headshot Url")
    hometown: str | None = Field(None, title="Hometown")
    id: int | None = Field(
        None, description="Player id; use with GET /v1/players/{player_id}.", title="Id"
    )
    is_verified: bool | None = Field(None, title="Is Verified")
    jersey_number: str | None = Field(None, title="Jersey Number")
    name: str | None = Field(None, title="Name")
    person_id: int | None = Field(None, title="Person Id")
    position: str | None = Field(None, title="Position")


class RosterPage(BaseModel):
    """
    One page of roster members from one season.
    """

    data: list[RosterEntry] = Field(..., title="Data")
    freshness: FreshnessInfo | None = Field(
        None, description="When this team's roster page was last read."
    )
    has_more: bool | None = Field(
        False, description="True when another page is available.", title="Has More"
    )
    next_cursor: str | None = Field(
        None,
        description="Opaque cursor for the next page; null when there are no more results.",
        examples=["eyJvZmZzZXQiOiAyNX0="],
        title="Next Cursor",
    )
    season: str | None = Field(
        None,
        description="Season of the returned roster; null when no roster is held.",
        title="Season",
    )


class SchoolRef(BaseModel):
    """
    The institution behind a team. `ipeds_unitid` is the federal IPEDS
    UNITID (NCES), the stable external key for joining to your own school
    records; it is null for schools outside the federal universe (some NAIA,
    junior-college, Canadian, and independent institutions).
    """

    athletics_domain: str | None = Field(
        None,
        description="The school's official athletics website domain (the source of its program data).",
        title="Athletics Domain",
    )
    city: str | None = Field(None, title="City")
    control: str | None = Field(
        None,
        description="Institutional control, e.g. 'Public' or 'Private nonprofit'.",
        title="Control",
    )
    id: int = Field(
        ..., description="School id; use with GET /v1/schools/{school_id}.", title="Id"
    )
    ipeds_unitid: int | None = Field(
        None,
        description="Federal IPEDS UNITID (NCES), when matched.",
        title="Ipeds Unitid",
    )
    name: str | None = Field(None, title="Name")
    slug: str | None = Field(None, description="Stable school slug.", title="Slug")
    state: str | None = Field(
        None, description="Two-letter US state code, when known.", title="State"
    )


class SchoolTeamRef(BaseModel):
    """
    One program a school fields, across every sport and division we hold.
    """

    conference: str | None = Field(None, title="Conference")
    division: str | None = Field(None, title="Division")
    id: int = Field(
        ...,
        description="Team id; scope-aware detail at GET /v1/teams/{team_id}.",
        title="Id",
    )
    logo_url: str | None = Field(None, title="Logo Url")
    name: str | None = Field(None, title="Name")
    sport_path: str | None = Field(None, title="Sport Path")


class SportEntry(BaseModel):
    """
    A supported sport and the genders it carries.
    """

    genders: list[str] = Field(..., examples=[["men", "women"]], title="Genders")
    sport: str = Field(..., examples=["soccer"], title="Sport")


class SportListResponse(BaseModel):
    """
    Envelope for GET /v1/sports.
    """

    data: list[SportEntry] = Field(..., title="Data")


class StringListResponse(BaseModel):
    """
    Envelope for simple string lists (divisions, conferences).
    """

    data: list[str] = Field(
        ...,
        description="String values returned by the reference endpoint.",
        examples=[["D1", "D1-FBS", "D1-FCS", "D2", "D3", "NAIA", "NJCAA-D1"]],
        title="Data",
    )


class TeamCoachEntry(BaseModel):
    """
    One member of a team's coaching staff for a season. `email` is populated
    only when the key delegates `outreach.coach.read` and the current actor's
    verified player role permits player-to-coach outreach for the sport.
    """

    bio_text: str | None = Field(
        None,
        description="Full biography published on the official coaching profile.",
        title="Bio Text",
    )
    bio_url: str | None = Field(
        None, description="Coach bio page on the school site.", title="Bio Url"
    )
    email: str | None = Field(
        None,
        description="Coach email; requires exact outreach.coach.read delegation and current verified player-role authority, else null.",
        title="Email",
    )
    headshot_url: str | None = Field(None, title="Headshot Url")
    id: int | None = Field(None, description="Coach id.", title="Id")
    is_head_coach: bool | None = Field(None, title="Is Head Coach")
    name: str | None = Field(None, title="Name")
    person_id: int | None = Field(
        None,
        description="Cross-school person cluster id, when linked.",
        title="Person Id",
    )
    phone: str | None = Field(
        None,
        description="Published coach phone; requires the same outreach authority as email.",
        title="Phone",
    )
    profile_slug: str | None = Field(
        None,
        description="Public profile slug on magisterial.ai, when minted.",
        title="Profile Slug",
    )
    role: str | None = Field(
        None,
        description="Staff title as published, e.g. 'Assistant Coach'.",
        title="Role",
    )
    season: str | None = Field(
        None, description="Season this staff row belongs to.", title="Season"
    )


class TeamCoachesResponse(BaseModel):
    """
    Envelope for GET /v1/teams/{team_id}/coaches. `season` is the season the
    staff list belongs to (the latest one held unless `season` was requested).
    """

    contacts_included: bool | None = Field(
        False,
        description="True when contact fields (email, phone) were populated for this request.",
        title="Contacts Included",
    )
    data: list[TeamCoachEntry] = Field(..., title="Data")
    freshness: FreshnessInfo | None = Field(
        None, description="When this team's staff page was last read."
    )
    season: str | None = Field(
        None,
        description="Season of the returned staff; null when no staff is held.",
        title="Season",
    )


class TeamFreshness(BaseModel):
    """
    Per data kind freshness for one team-program.
    """

    coaches: FreshnessInfo | None = None
    roster: FreshnessInfo | None = None
    schedule: FreshnessInfo | None = None
    season_stats: FreshnessInfo | None = None


class TeamSummary(BaseModel):
    """
    A team as returned by the teams list.
    """

    conference: str | None = Field(None, title="Conference")
    division: str | None = Field(None, title="Division")
    id: int | None = Field(
        None, description="Team id; use with GET /v1/teams/{team_id}.", title="Id"
    )
    logo_url: str | None = Field(None, title="Logo Url")
    name: str | None = Field(None, title="Name")
    school: SchoolRef | None = Field(
        None,
        description="The institution, with its IPEDS UNITID for joining to external records.",
    )
    sport_path: str | None = Field(
        None, description="Gendered sport key, e.g. 'mens-soccer'.", title="Sport Path"
    )


class TransferRecord(BaseModel):
    """
    One school-change edge in a person's cross-program career.
    """

    first_season_to: str | None = Field(
        None,
        description="First season at the destination school.",
        title="First Season To",
    )
    from_conference: str | None = Field(None, title="From Conference")
    from_division: str | None = Field(None, title="From Division")
    from_team_id: int | None = Field(
        None, description="Origin team id, when resolved.", title="From Team Id"
    )
    id: int | None = Field(None, title="Id")
    last_season_from: str | None = Field(
        None, description="Last season at the origin school.", title="Last Season From"
    )
    person_id: int | None = Field(None, title="Person Id")
    sport_path: str | None = Field(None, title="Sport Path")
    to_conference: str | None = Field(None, title="To Conference")
    to_division: str | None = Field(None, title="To Division")
    to_team_id: int | None = Field(
        None, description="Destination team id, when resolved.", title="To Team Id"
    )


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class AlertListResponse(BaseModel):
    """
    Envelope for GET /v1/alerts.
    """

    data: list[AlertSummary] = Field(..., title="Data")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class MovementEntry(BaseModel):
    """
    One roster/coaching movement event. The default `status=published` feed
    carries only events an editor (or the auto-publish policy) published; the
    Enterprise `resolved` and `observed` tiers expose the underlying resolver
    stream with its raw status, so a platform can act on same-day changes at
    its own confidence threshold.
    """

    division: str | None = Field(None, title="Division")
    event_type: str = Field(
        ...,
        description="player_added | player_removed | coach_added | coach_removed | title_changed",
        title="Event Type",
    )
    id: int = Field(..., title="Id")
    ipeds_unitid: int | None = Field(
        None,
        description="Federal IPEDS UNITID of the school, when matched.",
        title="Ipeds Unitid",
    )
    kind: str = Field(..., description="'player' or 'coach'.", title="Kind")
    observed_at: AwareDatetime | None = Field(
        None,
        description="When the roster or staff page change was observed by the scraper.",
        title="Observed At",
    )
    person_id: int | None = Field(
        None,
        description="Linked person, when the movement was resolved to one.",
        title="Person Id",
    )
    published_at: AwareDatetime | None = Field(
        None,
        description="When the event entered the curated feed; null until it does.",
        title="Published At",
    )
    resolution_kind: str | None = Field(
        None, description="e.g. 'head_coach_change_confirmed'.", title="Resolution Kind"
    )
    resolution_status: str | None = Field(
        None,
        description="Raw resolver outcome: linked_transfer | linked_move | new_freshman | new_hire | departed_unknown | roster_rollover | reappeared | pending.",
        title="Resolution Status",
    )
    resolved_at: AwareDatetime | None = Field(
        None,
        description="When identity resolution finished for this event.",
        title="Resolved At",
    )
    school_id: int | None = Field(
        None,
        description="School id; see GET /v1/schools/{school_id}.",
        title="School Id",
    )
    school_logo_url: str | None = Field(None, title="School Logo Url")
    school_name: str | None = Field(None, title="School Name")
    season: str | None = Field(None, title="Season")
    sport_path: str | None = Field(None, title="Sport Path")
    status: str | None = Field(
        None,
        description="'published' (curated feed), 'resolved' (identity resolution finished, not editorially published), or 'pending' (observed, awaiting resolution).",
        title="Status",
    )
    subject: MovementSubject
    team_id: int | None = Field(None, title="Team Id")
    transfer_id: int | None = Field(
        None,
        description="Transfer edge minted by this movement (players).",
        title="Transfer Id",
    )


class MovementPage(BaseModel):
    """
    One page of published movements.
    """

    data: list[MovementEntry] = Field(..., title="Data")
    has_more: bool | None = Field(
        False, description="True when another page is available.", title="Has More"
    )
    next_cursor: str | None = Field(
        None,
        description="Opaque cursor for the next page; null when there are no more results.",
        examples=["eyJvZmZzZXQiOiAyNX0="],
        title="Next Cursor",
    )


class PlayerSearchPage(BaseModel):
    """
    One page of player search results.
    """

    data: list[PlayerSummary] = Field(..., title="Data")
    has_more: bool | None = Field(
        False, description="True when another page is available.", title="Has More"
    )
    next_cursor: str | None = Field(
        None,
        description="Opaque cursor for the next page; null when there are no more results.",
        examples=["eyJvZmZzZXQiOiAyNX0="],
        title="Next Cursor",
    )


class SchoolDetail(BaseModel):
    """
    A school plus every program it fields.
    """

    athletics_domain: str | None = Field(
        None,
        description="The school's official athletics website domain (the source of its program data).",
        title="Athletics Domain",
    )
    city: str | None = Field(None, title="City")
    control: str | None = Field(
        None,
        description="Institutional control, e.g. 'Public' or 'Private nonprofit'.",
        title="Control",
    )
    id: int = Field(
        ..., description="School id; use with GET /v1/schools/{school_id}.", title="Id"
    )
    ipeds_unitid: int | None = Field(
        None,
        description="Federal IPEDS UNITID (NCES), when matched.",
        title="Ipeds Unitid",
    )
    name: str | None = Field(None, title="Name")
    slug: str | None = Field(None, description="Stable school slug.", title="Slug")
    state: str | None = Field(
        None, description="Two-letter US state code, when known.", title="State"
    )
    teams: list[SchoolTeamRef] | None = Field(None, title="Teams")


class SchoolPage(BaseModel):
    """
    A page of schools.
    """

    data: list[SchoolRef] = Field(..., title="Data")
    has_more: bool | None = Field(
        False, description="True when another page is available.", title="Has More"
    )
    next_cursor: str | None = Field(
        None,
        description="Opaque cursor for the next page; null when there are no more results.",
        examples=["eyJvZmZzZXQiOiAyNX0="],
        title="Next Cursor",
    )


class TeamDetail(BaseModel):
    """
    A single team plus its per-season document/stat records.
    """

    conference: str | None = Field(None, title="Conference")
    division: str | None = Field(None, title="Division")
    documents: Any | None = Field(
        None,
        description="Per-season team records (schedules, stats documents); shape varies by sport.",
        title="Documents",
    )
    freshness: TeamFreshness | None = Field(
        None,
        description="When each kind of source page for this program was last read.",
    )
    id: int | None = Field(
        None, description="Team id; use with GET /v1/teams/{team_id}.", title="Id"
    )
    logo_url: str | None = Field(None, title="Logo Url")
    name: str | None = Field(None, title="Name")
    school: SchoolRef | None = Field(
        None,
        description="The institution, with its IPEDS UNITID for joining to external records.",
    )
    sport_path: str | None = Field(
        None, description="Gendered sport key, e.g. 'mens-soccer'.", title="Sport Path"
    )


class TeamPage(BaseModel):
    """
    One page of teams.
    """

    data: list[TeamSummary] = Field(..., title="Data")
    has_more: bool | None = Field(
        False, description="True when another page is available.", title="Has More"
    )
    next_cursor: str | None = Field(
        None,
        description="Opaque cursor for the next page; null when there are no more results.",
        examples=["eyJvZmZzZXQiOiAyNX0="],
        title="Next Cursor",
    )


class TransferListResponse(BaseModel):
    """
    Envelope for GET /v1/persons/{person_id}/transfers.
    """

    data: list[TransferRecord] = Field(..., title="Data")
